Revert Go version to 1.22.0
nginxinc/telemetry-exporter pull request #120
Opened 2024-06-05 18:26 UTC by lucacome

### Proposed changes

This is a library so it will be compiled with the version specified in the project that imports it. This also is treated by Go as a minimum suggested version and we should only increase it if we need new features from the language. Bumping this to the latest version only means that the projects importing it will be forced to update to the same version.

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [ ] I have read the [CONTRIBUTING](https://github.com/nginxinc/telemetry-exporter/blob/main/CONTRIBUTING.md)
      guide
- [ ] I have proven my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have ensured the README is up to date
- [ ] I have rebased my branch onto main
- [ ] I will ensure my PR is targeting the main branch and pulling from my branch on my own fork

2024-06-05 20:54 UTC, sjberman approved these changes

2024-06-06 09:50 UTC, danielnginx commented
That fix security issues we should not revert it. https://go.dev/doc/devel/release#go1.22.4

2024-06-06 10:07 UTC, MichaelMcAleer commented
I second the comment from @danielnginx , we should not roll back here

2024-06-06 10:08 UTC, MichaelMcAleer requested changes

2024-06-06 10:08 UTC, MichaelMcAleer commented on go.mod
> -go 1.22.4
I agree with @danielnginx this should not be downgraded, the purpose of this bump is to consume Go stdlib vuln fixes.

Please reach out to Nginx security team with any questions.

2024-06-06 15:54 UTC, MichaelMcAleer commented on go.mod
> -go 1.22.4
Resolving after internal discussion on this.

2024-06-06 16:33 UTC, merged